### ISSUE TITLE
Setup automatic update when new image is deployed

### ISSUE THREAD

**Issue by jadlers** [jadlers/bollsvenskan-api#6]
Since #5 is in place an image is built when new code is merged into `main`. The second part of the CD pipeline is to configure the server to look for or be notified when a new image is available. It should then pull the new image and start the server again using the new version.

Some thoughts about ease of rollback to previous running image with documentation would also be nice.

**Comment by jadlers** [comment]
Could use [watchtower](https://containrrr.dev/watchtower/) for this.

**Comment by jadlers** [comment]
Watchtower is now running on the server. See the configuration used below. It checks for updates every minute. Building the image and pushing to docker hub takes less than 2m. This means that the time from push to server running the new version shouldn't be more than 4m.

```yaml
version: "3"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - TZ=Europe/Stockholm
    # Only monitor the following images
    command: bollsvenskan-api_api_server_1 # --debug
```

It's possible to run watchtower with push rather than poll using [HTTP API Mode](https://containrrr.dev/watchtower/arguments/#http_api_mode). Could be something to look into in the future.
